name: 编译 OpenWrt 固件

on:
  workflow_dispatch:
    inputs:
      device_name:
        description: '设备名称'
        required: true
        default: 'k2p'
      firmware_version:
        description: '固件版本'
        required: true
        default: '22.03'
      openwrt_source:
        description: 'OpenWrt 源码压缩包地址 (.tar.xz)'
        required: true
        default: 'https://mirror-03.infra.openwrt.org/releases/22.03.0/targets/ramips/mt7621/openwrt-sdk-22.03.0-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz'
      plugin_source:
        description: '插件源码地址'
        required: true
        default: 'https://github.com/sirpdboy/luci-app-netwizard.git'
      plugin_name:
        description: '编译后的插件名'
        required: true
        default: 'luci-app-netwizard-1.8.8'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
        gettext git java-propose-classpath libelf-dev libncurses5-dev \
        libncursesw5-dev libssl-dev python3 python3-distutils python3-setuptools \
        unzip wget rsync subversion swig time xsltproc zlib1g-dev

    - name: 设置 Python 软链接
      run: |
        sudo ln -sf /usr/bin/python3 /usr/bin/python

    - name: 下载并解压 OpenWrt 源码
      run: |
        wget ${{ github.event.inputs.openwrt_source }} -O openwrt.tar.xz
        mkdir openwrt
        tar -xJf openwrt.tar.xz -C openwrt --strip-components 1

    - name: 克隆插件源码
      run: git clone ${{ github.event.inputs.plugin_source }} plugin

    - name: 获取插件文件夹名称
      run: |
        echo "PLUGIN_FOLDER=$(ls plugin | head -n 1)" >> $GITHUB_ENV
        echo "插件文件夹名称: ${{ env.PLUGIN_FOLDER }}"

    - name: 复制插件到 OpenWrt 目录
      run: cp -r plugin/* openwrt/package/

    - name: 更新 feeds
      working-directory: openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 配置 OpenWrt
      working-directory: openwrt
      run: |
        # 启用指定的插件包
        echo "CONFIG_PACKAGE_${{ env.PLUGIN_FOLDER }}=m" >> .config
        
        # 生成完整的 .config 文件
        make defconfig

    - name: 列出插件目录结构
      working-directory: openwrt
      run: |
        echo "插件目录结构:"
        tree package/${{ env.PLUGIN_FOLDER }}
        echo "插件目录文件列表:"
        ls -lR package/${{ env.PLUGIN_FOLDER }}

    - name: 编译插件
      working-directory: openwrt
      run: |
        make package/${{ env.PLUGIN_FOLDER }}/compile V=s

    - name: 整理文件
      run: |
        mkdir -p firmware
        find openwrt/bin/packages/ -name "${{ env.PLUGIN_FOLDER }}*.ipk" | xargs -I {} mv {} firmware/
        cd firmware
        rename 's/^/${{ github.event.inputs.device_name }}-${{ github.event.inputs.firmware_version }}-/' *

    - name: 创建 Release
      uses: softprops/action-gh-release@v1
      with:
        files: firmware/*
        name: ${{ github.event.inputs.device_name }}-${{ github.event.inputs.firmware_version }}-${{ github.event.inputs.plugin_name }}
        tag_name: v${{ github.event.inputs.firmware_version }}-${{ github.event.inputs.plugin_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
