name: 编译 OpenWrt 固件

on:
  workflow_dispatch:
    inputs:
      device_name:
        description: '设备名称'
        required: true
      firmware_version:
        description: '固件版本'
        required: true
      openwrt_source:
        description: 'OpenWrt 源码压缩包地址 (.tar.xz)'
        required: true
      plugin_source:
        description: '插件源码地址'
        required: true
      plugin_name:
        description: '编译后的插件名'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
        gettext git java-propose-classpath libelf-dev libncurses5-dev \
        libncursesw5-dev libssl-dev python3 python3-distutils python3-setuptools \
        unzip wget rsync subversion swig time xsltproc zlib1g-dev

    - name: 设置 Python 软链接
      run: |
        sudo ln -sf /usr/bin/python3 /usr/bin/python

    - name: 下载并解压 OpenWrt 源码
      run: |
        wget ${{ github.event.inputs.openwrt_source }} -O openwrt.tar.xz
        mkdir openwrt
        tar -xJf openwrt.tar.xz -C openwrt --strip-components 1

    - name: 克隆插件源码
      run: git clone ${{ github.event.inputs.plugin_source }} plugin

    - name: 复制插件到 OpenWrt 目录
      run: cp -r plugin/* openwrt/package/

    - name: 更新 feeds
      working-directory: openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 配置 OpenWrt
      working-directory: openwrt
      run: |
        echo "CONFIG_TARGET_DEVICE=${{ github.event.inputs.device_name }}" >> .config
        echo "CONFIG_PACKAGE_${{ github.event.inputs.plugin_name }}=y" >> .config
        make defconfig

    - name: 编译固件
      working-directory: openwrt
      run: |
        make download -j8
        make -j$(nproc) || make -j1 V=s

    - name: 整理文件
      run: |
        mkdir -p firmware
        find openwrt/bin/targets/ -name "*sysupgrade.bin" -or -name "*factory.bin" | xargs -I {} mv {} firmware/
        cd firmware
        rename 's/^/${{ github.event.inputs.device_name }}-${{ github.event.inputs.firmware_version }}-${{ github.event.inputs.plugin_name }}-/' *

    - name: 创建 Release
      uses: softprops/action-gh-release@v1
      with:
        files: firmware/*
        name: ${{ github.event.inputs.device_name }}-${{ github.event.inputs.firmware_version }}-${{ github.event.inputs.plugin_name }}
        tag_name: v${{ github.event.inputs.firmware_version }}-${{ github.event.inputs.plugin_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
